### ISSUE TITLE
Response path always out of bounds on Windows

### ISSUE THREAD

**Issue by wimski** [swisnl/php-http-fixture-client#13]
[ResponseBuilder:174](https://github.com/swisnl/php-http-fixture-client/blob/7dceb4fc74efb20a1940a1b667670d8188706048/src/ResponseBuilder.php#L174-L176) will always throw an exception on Windows even if the path is valid.

```php
if (realpath(\dirname($file)) !== \dirname($file)) {
    throw new \RuntimeException(sprintf('Path to file "%s" is out of bounds.', $file));
}
```

This is because `realpath` in Windows will have backslashes as a directory separator between all directories, whereas `dirname` will only have backslashes for the part that's not already in the `$file` path.

```php
realpath(\dirname($file)); // C:\dev\my-project\tests\stubs\responses\some-website.com\endpoint\123.get.mock
\dirname($file);           // C:\dev\my-project\tests\stubs\responses/some-website.com/endpoint/123.get.mock
```

Is there a reason for this specific condition instead of just `file_exists()`?

```php
if (! file_exists($file)) {
    throw new \RuntimeException(sprintf('Path to file "%s" is out of bounds.', $file));
}
```

**Comment by JaZo** [comment]
@wimski, thanks for reporting this issue, I'll look into it! This check is to prevent a directory traversal attack by making sure you can't break out of the fixtures directory and access arbitrary files.

**Comment by JaZo** [comment]
@wimski A fix has been merged into master. Can you confirm this issue is fixed?
